# Generated by Django 4.2.3 on 2023-10-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='book_pdfs')),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='book_images')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
